# Generated by Django 4.2.1 on 2023-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contatos_options_contatos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
